name: Hous PR Builder

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    name: PR Checker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Gradle cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

#    - name: Create Google-Services.json
#      env:
#        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
#      run: |
#        touch ./app/google-services.json
#        echo $GOOGLE_SERVICES >> ./app/google-services.json
#        cat ./app/google-services.json
#
    - name: Create Local Properties
      run: touch local.properties

    - name: Access Local Properties
      env:
        FUNCH_DEBUG_BASE_URL: ${{ secrets.FUNCH_DEBUG_BASE_URL }}
#        HOST_RELEASE_URI: ${{ secrets.HOST_RELEASE_URI }}
#        KAKAO_NATIVE_APP_KEY: ${{ secrets.KAKAO_NATIVE_APP_KEY }}
#        KAKAO_REDIRECT_SCHEME: ${{ secrets.KAKAO_REDIRECT_SCHEME }}
#        KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        STORE_FILE: ${{ secrets.STORE_FILE }}
      run: |
        echo FUNCH_DEBUG_BASE_URL=\"FUNCH_DEBUG_BASE_URL\" >> local.properties
#        echo HOST_RELEASE_URI=\"$HOST_RELEASE_URI\" >> local.properties
#        echo KAKAO_NATIVE_APP_KEY=\"$KAKAO_NATIVE_APP_KEY\" >> local.properties
#        echo KAKAO_REDIRECT_SCHEME=\"$KAKAO_REDIRECT_SCHEME\" >> local.properties
#        echo KEYSTORE_PATH= $KEYSTORE_PATH >> local.properties
        echo STORE_PASSWORD= $STORE_PASSWORD >> local.properties
        echo KEY_PASSWORD= $KEY_PASSWORD >> local.properties
        echo KEY_ALIAS= $KEY_ALIAS >> local.properties
        echo STORE_FILE= $STORE_FILE >> local.properties

    - name: Create keystore
      run: |
        mkdir -p app/keystore
        touch app/keystore/hous_key.jks

    - name: decode release keystore
      run: echo "${{ secrets.STORE_FILE }}" | base64 -d > keystore/funch_key_store.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Lint Check
      run: ./gradlew ktlintCheck

    - name: run rest
      run: ./gradlew test

    - name: Build with Gradle
      run: ./gradlew build
